GET http://localhost:3000/api/saved-posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsImVtYWlsIjoicHlhZXBza0BnbWFpbC5jb20iLCJpYXQiOjE3MzM5Mjc0NTAsImV4cCI6MTczMzkzMTA1MCwiYXVkIjoibG9jYWxob3N0IiwiaXNzIjoibG9jYWxob3N0In0.mM8x5zdYMZsLd6rT_oUwOJCQ0R_oiXMBz02SpmZsJWc

POST http://localhost:3000/api/saved-posts/3/save
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsImVtYWlsIjoicHlhZXBza0BnbWFpbC5jb20iLCJpYXQiOjE3MzM5MjUzNjMsImV4cCI6MTczMzkyODk2MywiYXVkIjoibG9jYWxob3N0IiwiaXNzIjoibG9jYWxob3N0In0.h4wdRb5jjgSFS4iUhakNPjcWGaViuA6jOadCvfyVKoo

POST http://localhost:3000/api/saved-posts/2/unsave
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsImVtYWlsIjoicHlhZXBza0BnbWFpbC5jb20iLCJpYXQiOjE3MzM5MjUzNjMsImV4cCI6MTczMzkyODk2MywiYXVkIjoibG9jYWxob3N0IiwiaXNzIjoibG9jYWxob3N0In0.h4wdRb5jjgSFS4iUhakNPjcWGaViuA6jOadCvfyVKoo