GET http://localhost:3000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoid29vZGlAZ21haWwuY29tIiwiaWF0IjoxNzMyNzYzMzQxLCJleHAiOjE3MzI3NjY5NDEsImF1ZCI6ImxvY2FsaG9zdCIsImlzcyI6ImxvY2FsaG9zdCJ9.7Tkxpby5Si1eOOWH_FrSBZaBEEj0_YbBKaTjGhDVhrk
GET http://localhost:3000/api/users/mario_m/details

GET http://localhost:3000/api/users/popular-authors

PATCH http://localhost:3000/api/users/change-username
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoid29vZGlAZ21haWwuY29tIiwiaWF0IjoxNzMyNzI0OTcwLCJleHAiOjE3MzI3Mjg1NzAsImF1ZCI6ImxvY2FsaG9zdCIsImlzcyI6ImxvY2FsaG9zdCJ9.6tCYhnwiP87hrg8vJv35hzW_Z1WXlzCB-t_qKN2qxos

{
    "name": "Woodi",
    "username": "woodi_wd"
}

PATCH http://localhost:3000/api/users/2/change-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoid29vZGlAZ21haWwuY29tIiwiaWF0IjoxNzMyNzYzMzQxLCJleHAiOjE3MzI3NjY5NDEsImF1ZCI6ImxvY2FsaG9zdCIsImlzcyI6ImxvY2FsaG9zdCJ9.7Tkxpby5Si1eOOWH_FrSBZaBEEj0_YbBKaTjGhDVhrk

{
    "oldPassword": "M@rio111111",
    "newPassword": "M@rio111111"
}