GET http://localhost:3000/api/users


GET http://localhost:3000/api/users/1/posts


POST http://localhost:3000/api/users
Content-Type: application/json

{
    "name": "Mario",
    "email": "mario@gmail.com",
    "password": "M@rio111111",
    "username": "mario_m"
}


PATCH http://localhost:3000/api/users/1
Content-Type: application/json

{
    "name": "Woodi",
    "username": "woodi_wd"
}