POST http://localhost:3000/api/auth/sign-up
Content-Type: application/json
{
    "name": "Pyaesone",
    "username": "pk_ares",
    "email": "pyaepsk@gmail.com",
    "password": "Asdfghjkl!1"
}

POST http://localhost:3000/api/auth/sign-in
Content-Type: application/json
{
    "email": "woodi@gmail.com",
    "password": "Asdfghjkl!1"
}


POST http://localhost:3000/api/auth/verify-otp
Content-Type: application/json

{
    "email": "woodi@gmail.com",
    "otp": "345375"
}

POST http://localhost:3000/api/auth/request-otp
Content-Type: application/json

{
    "email": "woodi@gmail.com"
}


POST http://localhost:3000/api/auth/forgot-password
Content-Type: application/json

{
    "email": "woodi@gmail.com"
}

