POST http://localhost:3000/api/auth/sign-in
Content-Type: application/json

{
    "email": "woodi@gmail.com",
    "password": "Asdfghjkl!1"
}

POST http://localhost:3000/api/auth/sign-up
Content-Type: application/json

{
    "name": "Woodi",
    "email": "woodi@gmail.com",
    "password": "Asdfghjkl!1",
    "username": "woodi_wd"
}